# Generated by Django 5.2.7 on 2025-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('diocesan', 'Diocesan'), ('congregation', 'Congregation')], default='diocesan', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='congregation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='diocese',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
