# Generated by Django 5.2.7 on 2025-11-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_student_type_alter_student_congregation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name_of_study',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='year_completed',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
