# Generated by Django 5.2.7 on 2025-11-26 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_name_of_study_student_year_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='EnrollmentRequirement',
        ),
        migrations.DeleteModel(
            name='ExamInformation',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='SpiritualGuidance',
        ),
        migrations.DeleteModel(
            name='TuitionFee',
        ),
    ]
