"""
Django settings for hsms project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import Config, RepositoryEnv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Explicitly load .env from BASE_DIR to ensure it is found in production
env_path = BASE_DIR / '.env'
if env_path.exists():
    config = Config(RepositoryEnv(str(env_path)))
else:
    from decouple import config


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-1jbm$@xlw)6lfr_&3qlb*(wp0eu7vvi6cyw4y4^rus%#s3sevm')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',') if config('ALLOWED_HOSTS', default='') else []

ENVIRONMENT = config('ENVIRONMENT', default='development')


# Application definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
]

THIRD_PARTY_APPS = [
    'django_htmx',
    'tinymce',
    'django_select2',
    # Removed 'modeltranslation'
]

LOCAL_APPS = [
    'seminary',
    'library',
    'students',
    'spiritual_food',
    'utils',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # For i18n support
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Removed 'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'library.middleware.LibrarySecurityMiddleware',
    'library.middleware.BorrowingActivityLogger',
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/library.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'library': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = 'hsms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Seminary context processors
                'seminary.context_processors.site_settings',
                'seminary.context_processors.global_announcements',
                'seminary.context_processors.navigation_pages',
                'seminary.context_processors.breadcrumb_helper',
                'django.template.context_processors.i18n', 
                'library.context_processors.library_stats', 
            ],
        },
    },
]

WSGI_APPLICATION = 'hsms.wsgi.application'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Cache configuration for production

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'library',
        'VERSION': 1,
    }
}
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if ENVIRONMENT == 'production':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='your_database_name'),
            'USER': config('DB_USER', default='your_username'),
            'PASSWORD': config('DB_PASSWORD', default='your_password'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432', cast=str),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Dhaka'
USE_I18N = True
USE_TZ = True

USE_L10N = True


# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('bn', 'বাংলা'),
]

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'width': '100%',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'silver',
    'plugins': '''
        save link image media preview codesample contextmenu
        table code lists fullscreen insertdatetime nonbreaking
        directionality searchreplace wordcount visualblocks
        visualchars fullscreen autolink charmap anchor pagebreak
    ''',
    'toolbar': '''
        undo redo | formatselect | bold italic underline strikethrough | 
        forecolor backcolor | alignleft aligncenter alignright alignjustify | 
        bullist numlist outdent indent | removeformat | link image media table | 
        code fullscreen preview
    ''',
    'menubar': 'file edit view insert format tools table',
    'statusbar': True,
    'branding': False,
    'convert_urls': False,
    'relative_urls': False,
    'content_css': '/static/css/tinymce-content.css',
    'content_style': '''
        body { font-family: Inter, sans-serif; font-size: 16px; }
    ''',
    'valid_elements': '*[*]',  # Allow all elements and attributes including style
    'extended_valid_elements': '*[*]',
    'valid_children': '+body[style]',
    'retain_style_properties': 'color,background-color,font-size,font-family,text-align',
    'formats': {
        'forecolor': {'inline': 'span', 'styles': {'color': '%value'}},
        'hilitecolor': {'inline': 'span', 'styles': {'background-color': '%value'}},
    },
    'color_map': [
        '#BFEDD2', 'Light Green',
        '#FBEEB8', 'Light Yellow',
        '#F8CAC6', 'Light Red',
        '#ECCAFA', 'Light Purple',
        '#C2E0F4', 'Light Blue',
        '#2DC26B', 'Green',
        '#F1C40F', 'Yellow',
        '#E03E2D', 'Red',
        '#B96AD9', 'Purple',
        '#3598DB', 'Blue',
        '#169179', 'Dark Turquoise',
        '#E67E23', 'Orange',
        '#BA372A', 'Dark Red',
        '#843FA1', 'Dark Purple',
        '#236FA1', 'Dark Blue',
        '#ECF0F1', 'Light Gray',
        '#CED4D9', 'Medium Gray',
        '#95A5A6', 'Gray',
        '#7E8C8D', 'Dark Gray',
        '#34495E', 'Navy Blue',
        '#000000', 'Black',
        '#FFFFFF', 'White'
    ],
    'color_cols': 5,
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration - Gmail SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('GMAIL_USER', 'hsmsmajorseminary@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('GMAIL_APP_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('GMAIL_USER', 'hsmsmajorseminary@gmail.com')
SERVER_EMAIL = os.getenv('GMAIL_USER', 'hsmsmajorseminary@gmail.com')



# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 86400
    SECURE_REDIRECT_EXEMPT = []
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_TZ = True
    
    # CSRF settings
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    
    # Session settings
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True

# Caching (for production)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

SELECT2_CACHE_BACKEND = "default"

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',  # Important for Unicode logging
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
            'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'library': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# Library-specific settings for multilingual support
LIBRARY_SETTINGS = {
    'DEFAULT_LANGUAGE': 'en',
    'SUPPORTED_LANGUAGES': ['en', 'bn', 'mixed'],
    'AUTO_DETECT_LANGUAGE': True,
    'ENABLE_TRANSLITERATION': False,  # Set to True if you want to add transliteration features
    'SEARCH_MIN_CHARS': 2,
    'SEARCH_CACHE_TIMEOUT': 300,  # 5 minutes
    'BOOKS_PER_PAGE': 16,
    'QUICK_SEARCH_RESULTS': 10,
    'LOAN_PERIOD_DAYS': 14,  # Default loan period
    'MAX_RENEWALS': 2,  # Maximum number of renewals
    'MAX_BOOKS_PER_USER': 5,  # Maximum books a user can borrow
    'FINE_PER_DAY': 10.00,  # Fine amount per day (in BDT)
    'FIRST_REMINDER_DAYS': 3,  # Days before due date to send first reminder
    'SECOND_REMINDER_DAYS': 1,  # Days before due date to send second reminder
    'OVERDUE_REMINDER_INTERVAL': 7,  # Send overdue notice every X days

    'DEFAULT_LOAN_PERIOD': 14,  # days
    'DEFAULT_RENEWAL_PERIOD': 14,  # days
    'OVERDUE_FINE_PER_DAY': 10.00,  # BDT
    'SEND_EMAIL_REMINDERS': True,
    'REMINDER_DAYS_BEFORE_DUE': [3, 1],  # Send reminders 3 and 1 days before due
}

# Default From Email
DEFAULT_FROM_EMAIL = 'library@hsms.edu'
SERVER_EMAIL = 'library@hsms.edu'

# Email Subject Prefix
EMAIL_SUBJECT_PREFIX = '[HSMS Library] '

# Borrowing Settings
LIBRARY_LOAN_PERIOD_DAYS = 14
LIBRARY_MAX_RENEWALS = 2
LIBRARY_MAX_BOOKS_PER_USER = 5
LIBRARY_FINE_PER_DAY = 10.00  # In BDT

# Email Reminder Days Before Due Date
LIBRARY_FIRST_REMINDER_DAYS = 3
LIBRARY_SECOND_REMINDER_DAYS = 1

# Font settings for different languages
FONT_SETTINGS = {
    'bangla': {
        'primary': 'Noto Sans Bengali',
        'fallback': ['SutonnyMJ', 'Kalpurush', 'sans-serif'],
        'web_font_url': 'https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@300;400;500;600;700&display=swap'
    },
    'english': {
        'primary': 'Inter',
        'fallback': ['-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'web_font_url': 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap'
    }
}

# CSV Import settings
CSV_IMPORT_SETTINGS = {
    'MAX_FILE_SIZE': 10 * 1024 * 1024,  # 10MB
    'ALLOWED_ENCODINGS': ['utf-8', 'utf-8-sig', 'utf-16', 'cp1252'],
    'DEFAULT_ENCODING': 'utf-8',
    'CHUNK_SIZE': 1000,  # Process books in chunks
    'AUTO_DETECT_ENCODING': True,
}

# Search settings
SEARCH_SETTINGS = {
    'ENABLE_POSTGRESQL_SEARCH': True,  # Set to False if not using PostgreSQL
    'SEARCH_RANK_THRESHOLD': 0.1,
    'MAX_SEARCH_RESULTS': 100,
    'HIGHLIGHT_SEARCH_TERMS': True,
    'SEARCH_FIELDS': {
        'high_priority': ['title', 'title_bangla'],
        'medium_priority': ['subtitle', 'subtitle_bangla', 'authors'],
        'low_priority': ['keywords', 'keywords_bangla', 'isbn', 'call_number'],
    }
}

# Performance settings
PERFORMANCE_SETTINGS = {
    'ENABLE_QUERY_OPTIMIZATION': True,
    'USE_SELECT_RELATED': True,
    'USE_PREFETCH_RELATED': True,
    'CACHE_QUERY_RESULTS': True,
    'CACHE_TIMEOUT_SHORT': 300,    # 5 minutes
    'CACHE_TIMEOUT_MEDIUM': 900,   # 15 minutes
    'CACHE_TIMEOUT_LONG': 3600,    # 1 hour
}
# Security settings for file uploads
ALLOWED_UPLOAD_EXTENSIONS = ['.csv', '.xlsx', '.xls']
MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB

# File upload settings
FILE_UPLOAD_PERMISSIONS = 0o644
THUMBNAIL_SIZE = (800, 600)  

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024  # 200MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024  # 200MB
MAX_VIDEO_UPLOAD_SIZE = 200 * 1024 * 1024  # 200MB

GALLERY_SETTINGS = {
    'MAX_VIDEO_SIZE': 200 * 1024 * 1024,  # 200MB
    'MAX_IMAGE_SIZE': 10 * 1024 * 1024,   # 10MB
    'ALLOWED_VIDEO_FORMATS': ['.mp4', '.avi', '.mov', '.wmv', '.mkv', '.webm'],
    'ALLOWED_IMAGE_FORMATS': ['.jpg', '.jpeg', '.png', '.gif', '.webp'],
}

# Default charset for file operations
DEFAULT_CHARSET = 'utf-8'

# Pagination settings
PAGINATE_BY = 16
PAGINATE_ORPHANS = 3

LOGIN_REDIRECT_URL = '/library/'
LOGOUT_REDIRECT_URL = '/'

# Message tags for Bootstrap styling
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}