# Generated by Django 5.2.5 on 2025-10-06 15:23

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(help_text='Brief description for scrolling display', max_length=300)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF'), ('image', 'Image')], default='text', max_length=10)),
                ('text_content', tinymce.models.HTMLField(blank=True, help_text='Full text content', null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='announcements/pdfs/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='announcements/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for no expiration', null=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('bank', 'Bank Transfer'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(blank=True, help_text='For bank transfers', max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for donors')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='donation/qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Donation Information',
                'verbose_name_plural': 'Donation Information',
                'ordering': ['order', 'payment_method'],
            },
        ),
        migrations.CreateModel(
            name='HomilyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Homily Category',
                'verbose_name_plural': 'Homily Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('request_type', models.CharField(choices=[('prayer', 'Prayer Intention'), ('mass', 'Mass Intention'), ('thanksgiving', 'Thanksgiving'), ('healing', 'Healing'), ('guidance', 'Guidance'), ('other', 'Other')], max_length=20)),
                ('intention', models.TextField(help_text='Please describe your prayer intention')),
                ('preferred_date', models.DateField(blank=True, help_text='For Mass intentions', null=True)),
                ('make_public', models.BooleanField(default=False, help_text='Allow this intention to be shared publicly')),
                ('wants_to_donate', models.BooleanField(default=False)),
                ('donation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('donation_reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('prayed', 'Prayed For')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prayer Request',
                'verbose_name_plural': 'Prayer Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('mass', 'Holy Mass'), ('adoration', 'Eucharistic Adoration'), ('rosary', 'Holy Rosary'), ('vespers', 'Evening Prayer (Vespers)'), ('lauds', 'Morning Prayer (Lauds)'), ('compline', 'Night Prayer (Compline)'), ('novena', 'Novena'), ('other', 'Other')], max_length=20)),
                ('day', models.CharField(choices=[('daily', 'Daily'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('special', 'Special Occasion')], max_length=20)),
                ('time', models.TimeField()),
                ('location', models.CharField(default='Chapel', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Prayer Service',
                'verbose_name_plural': 'Prayer Services',
                'ordering': ['order', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Homily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('preacher', models.CharField(help_text='Name of the preacher', max_length=200)),
                ('date', models.DateField()),
                ('liturgical_season', models.CharField(blank=True, choices=[('advent', 'Advent'), ('christmas', 'Christmas'), ('ordinary', 'Ordinary Time'), ('lent', 'Lent'), ('easter', 'Easter'), ('special', 'Special Feasts')], max_length=20)),
                ('sunday_reading', models.CharField(blank=True, help_text='e.g., 3rd Sunday of Advent', max_length=100)),
                ('scripture_reference', models.CharField(blank=True, help_text='e.g., Matthew 5:1-12', max_length=300)),
                ('summary', models.TextField(help_text='Brief summary for preview', max_length=500)),
                ('text_content', tinymce.models.HTMLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='Full YouTube video URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='homilies/thumbnails/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spiritual_food.homilycategory')),
            ],
            options={
                'verbose_name': 'Homily',
                'verbose_name_plural': 'Homilies',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date'], name='spiritual_f_date_2aacae_idx'), models.Index(fields=['liturgical_season'], name='spiritual_f_liturgi_c5c4a7_idx')],
            },
        ),
    ]
