# Generated by Django 5.2.5 on 2025-10-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritual_food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_email_notifications', models.BooleanField(default=True, help_text='Enable to send prayer requests to a designated email address.')),
                ('notification_email', models.EmailField(blank=True, help_text='The email address to receive prayer request notifications.', max_length=254)),
                ('keep_a_copy', models.BooleanField(default=True, help_text='Save a copy of each prayer request in the admin panel.')),
            ],
            options={
                'verbose_name': 'Prayer Request Settings',
                'verbose_name_plural': 'Prayer Request Settings',
            },
        ),
    ]
