# Generated by Django 5.2.7 on 2025-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritual_food', '0002_prayerrequestsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiturgicalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('solemnity', 'Solemnity'), ('feast', 'Feast'), ('memorial', 'Memorial'), ('optional-memorial', 'Optional Memorial'), ('sunday', 'Sunday'), ('weekday', 'Weekday')], default='weekday', max_length=20)),
                ('is_holy_day_of_obligation', models.BooleanField(default=False, help_text='Is this a holy day of obligation?')),
            ],
            options={
                'verbose_name': 'Liturgical Calendar Event',
                'verbose_name_plural': 'Liturgical Calendar Events',
                'ordering': ['date'],
            },
        ),
    ]
