# Generated by Django 5.2.7 on 2025-11-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritual_food', '0003_liturgicalcalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('feast_day', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='liturgicalcalendar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='liturgicalcalendar',
            name='event_type',
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('white', 'White'), ('red', 'Red'), ('violet', 'Violet'), ('rose', 'Rose')], default='green', max_length=10),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='cycle',
            field=models.CharField(blank=True, choices=[('A', 'Year A'), ('B', 'Year B'), ('C', 'Year C'), ('I', 'Year I'), ('II', 'Year II')], max_length=2),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='first_reading',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='gospel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='rank',
            field=models.CharField(choices=[('solemnity', 'Solemnity'), ('sunday', 'Sunday'), ('feast', 'Feast'), ('memorial', 'Memorial'), ('optional-memorial', 'Optional Memorial'), ('weekday', 'Weekday')], default='weekday', max_length=20),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='responsorial_psalm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='season',
            field=models.CharField(blank=True, choices=[('advent', 'Advent'), ('christmas', 'Christmas'), ('ordinary', 'Ordinary Time'), ('lent', 'Lent'), ('easter', 'Easter')], max_length=20),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='second_reading',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='liturgicalcalendar',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='saints',
            field=models.ManyToManyField(blank=True, to='spiritual_food.saint'),
        ),
    ]
