# Generated by Django 5.0.2 on 2026-08-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritual_food', '0004_saint_remove_liturgicalcalendar_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='alt_first_reading',
            field=models.CharField(blank=True, help_text='Alternative 1st Reading', max_length=100),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='alt_gospel',
            field=models.CharField(blank=True, help_text='Alternative Gospel', max_length=100),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='alt_reading_title',
            field=models.CharField(blank=True, help_text="Title for alternative readings, e.g. 'Or Common of Saints' / 'অথবা বাণীবিতান'", max_length=200),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='alt_responsorial_psalm',
            field=models.CharField(blank=True, help_text='Alternative Psalm', max_length=100),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='alt_second_reading',
            field=models.CharField(blank=True, help_text='Alternative 2nd Reading', max_length=100),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='commemorations',
            field=models.TextField(blank=True, help_text='Local diocese/seminary commemorations or necrology (+ deceased priests/religious)'),
        ),
        migrations.AddField(
            model_name='liturgicalcalendar',
            name='secondary_color',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('white', 'White'), ('red', 'Red'), ('violet', 'Violet'), ('rose', 'Rose')], help_text='Optional secondary color (e.g. White when primary color is Green)', max_length=10, null=True),
        ),
    ]
