# Generated by Django 5.2.5 on 2025-09-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0008_seminaryadministration_alter_news_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hsit_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
