# Generated by Django 5.2.5 on 2025-10-09 05:46

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify

def forwards_func(apps, schema_editor):
    Committee = apps.get_model("seminary", "Committee")
    CommitteeType = apps.get_model("seminary", "CommitteeType")
    for committee in Committee.objects.all():
        if committee.committee_type:
            committee_type_name = committee.committee_type
            committee_type, created = CommitteeType.objects.get_or_create(
                name=committee_type_name,
                defaults={'slug': slugify(committee_type_name)}
            )
            committee.committee_type_new = committee_type
            committee.save()

def backwards_func(apps, schema_editor):
    Committee = apps.get_model("seminary", "Committee")
    for committee in Committee.objects.all():
        if committee.committee_type_new:
            committee.committee_type = committee.committee_type_new.name
            committee.save()

class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0009_sitesettings_hsit_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='committee',
            name='committee_type_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees_new', to='seminary.committeetype'),
        ),
        migrations.RunPython(forwards_func, backwards_func),
        migrations.RemoveField(
            model_name='committee',
            name='committee_type',
        ),
        migrations.RenameField(
            model_name='committee',
            old_name='committee_type_new',
            new_name='committee_type',
        ),
        migrations.AlterField(
            model_name='committee',
            name='committee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees', to='seminary.committeetype'),
        ),
    ]
