# Generated by Django 5.2.5 on 2025-10-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0010_committeetype_alter_committee_committee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeetype',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
