# Generated by Django 5.2.5 on 2025-10-11 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0011_committeetype_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='video_file',
            field=models.FileField(blank=True, help_text='Maximum file size: 200MB. Supported formats: MP4, AVI, MOV, WMV, MKV, WEBM', null=True, upload_to='gallery/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'mkv', 'webm'])]),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['gallery', 'order'], name='seminary_ga_gallery_f20c08_idx'),
        ),
    ]
