# Generated by Django 5.2.7 on 2025-10-13 15:45

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0012_alter_galleryitem_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('event_type', models.CharField(blank=True, choices=[('academic', 'Academic'), ('holiday', 'Holiday'), ('meeting', 'Meeting'), ('other', 'Other')], max_length=50)),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
