# Generated by Django 5.2.7 on 2025-11-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0013_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name to identify the banner (e.g., 'publications', 'news').", max_length=100, unique=True)),
                ('image', models.ImageField(help_text='Upload a banner image. Recommended size: 1920x400 pixels.', upload_to='banners/')),
                ('title', models.CharField(blank=True, help_text='Optional: A title to display on the banner.', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional: A subtitle to display on the banner.', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this banner.')),
            ],
        ),
    ]
