# Generated by Django 5.2.7 on 2025-11-25 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0014_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='name',
        ),
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('publications', 'Publications'), ('news', 'News'), ('events', 'Events'), ('gallery', 'Gallery'), ('contact', 'Contact'), ('about', 'About'), ('spiritual-food', 'Spiritual Food'), ('default-banner', 'Default Banner')], default=django.utils.timezone.now, help_text='Select the page where this banner will be displayed.', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
