# Generated by Django 5.2.7 on 2025-11-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminary', '0015_remove_banner_name_banner_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('publications', 'Publications'), ('news', 'News'), ('events', 'Events'), ('gallery', 'Gallery'), ('contact', 'Contact'), ('about', 'About'), ('spiritual-food', 'Spiritual Food'), ('seminary-history', 'Seminary History'), ('formation-program', 'Formation Program'), ('rules-regulations', 'Rules & Regulations'), ('committees', 'Committees'), ('philosophy-department', 'Philosophy Department'), ('church-history', 'Church History'), ('local-church-history', 'Local Church History'), ('theology-department', 'Theology Department'), ('default-banner', 'Default Banner')], help_text='Select the page where this banner will be displayed.', max_length=50, unique=True),
        ),
    ]
